language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ViniNepo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ViniNepo/docker-react npm run test